name: Lint

on:
  push:
    branches-ignore: [develop, main]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        name: Pull branch
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Checking lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
