name: Test for FE

on:
  push:
    branches: ["*"]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        name: Pull branch
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Checking test
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test -- --passWithNoTests
