name: Test

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - run: npm test -- --passWithNoTests
